### ISSUE TITLE
Upgrade for pgx/v4,please

### ISSUE THREAD

**Issue by OliverZou** [vgarvardt/pgx-helpers#4]
since helpers can't get FieldDescriptions fron a row

**Comment by vgarvardt** [comment]
Thank you for reporting the issue. I'll be able to handle it next week.

**Comment by vgarvardt** [comment]
There are two news - the good one and the second one.

The good one - PoC kinda works (see attached PR).

The second one - I would not use for production - too much unsafe/reflection magic to make `ScanStruct` work because of the pgx implementation changes.

If you really need this - I can remove `ScanStruct` implementation in the first v4-compatible version completely so you could use `conn.Query()`/`ScanStructs()` even for single-row results as its implementation does not require any ~black~ unsafe/reflection magic. In the mean time I'll try to contact `pgx` maintainers to see if the `Row` interface can be extended somehow to allow let `ScanStruct` work again.

**Comment by vgarvardt** [comment]
Tagged v4 with `ScanStructs` support only bsed on the discussion in https://github.com/jackc/pgx/issues/627
